# Rename, count, and pull top mentions
# by: Adam Rector
# updated 3/16/2021

library(tidyverse)

# define where you are working
setwd("C:/class/newdata")

## read in the clustered csv file that was generated by OpenRefine

filepath <- choose.files(multi=F, caption="Choose File To Import", filters = Filters[c("All"),] ) 

data <- read.csv(file = filepath)

## manually clean up some of the top duplicate mentions that clustering didn't get
# run the SPSS rename function over every cell in the softwares column
data$software <- sapply(data$software, function(x) str_replace_all(x, "'spss statistics'", "'spss'"))
data$software <- sapply(data$software, function(x) str_replace_all(x, "'statistical package for social sciences \\(spss\\)'", "'spss'"))
data$software <- sapply(data$software, function(x) str_replace_all(x, "'statistical package for the social sciences \\(spss\\)'", "'spss'"))

# run the R rename function over every cell in the softwares column
data$software <- sapply(data$software, function(x) str_replace_all(x, "'rstudio'", "'r'"))
data$software <- sapply(data$software, function(x) str_replace_all(x, "'r foundation for statistical computing'", "'r'"))
data$software <- sapply(data$software, function(x) str_replace_all(x, "'r foundation for statistical'", "'r'"))

# run the graphpad rename function over every cell in the softwares column
data$software <- sapply(data$software, function(x) str_replace_all(x, "'graphpad prism'", "'graphpad'"))
data$software <- sapply(data$software, function(x) str_replace_all(x, "'prism'", "'graphpad'"))

# run the blast rename function over every cell in the softwares column
data$software <- sapply(data$software, function(x) str_replace_all(x, "'blastn'", "'blast'"))
data$software <- sapply(data$software, function(x) str_replace_all(x, "'blastp'", "'blast'"))

# run the autodock rename function over every cell in the softwares column
data$software <- sapply(data$software, function(x) str_replace_all(x, "'autodock vina'", "'autodock'"))

#rerun the duplicate removal now that some software mentions have been renamed
data$software <- sapply(data$software, function(x) paste(unique(unlist(strsplit(x, ", "))), collapse = ", "))

# remove the apostrophes
data$software <- sapply(data$software, function(x) str_replace_all(x, "\\'", ""))


# write the reclustered dataset to a csv
write.csv(data,"software_reclustered.csv", row.names = FALSE)


## using the reclustered data
## get counts of the most common softwares
# create a single text string of all software mentions
softwares <- paste(unlist(strsplit(data$software, ", ")), collapse = ", ")
softwares <- as.list(strsplit(softwares, ", "))

# order the software by counts
tab <- table(softwares)
software_ranks <- as.data.frame(tab)
names(software_ranks) <- c("software","times")
software_ranks$rank <- rank(-software_ranks$times,ties.method="min")
software_ranks <- software_ranks[order(software_ranks$rank,decreasing = F),]

## create a list of the top softwares
topcounts <- subset(software_ranks, (rank <= 20))
# get a dataframe for the comparison later
topsoftwares <- subset(topcounts, select=(software))

# write the count datasets to csv
write.csv(software_ranks, "total_software_mentions.csv", row.names = FALSE)
write.csv(topcounts,"top_counts.csv", row.names = FALSE)

## for fun, create a word cloud of the top softwares

library(wordcloud)

wordcloud(words = topcounts$software, freq = topcounts$times, min.freq = 100,
          max.words=100, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))


## Create a new data set of just the articles mentioning the top software
## for each cell in the software column, remove every software mention that isn't in the top list

#create a new data frame for the reduced data

culled_data <- data

#create a function for taking a text list of softwares, comparing it to the top list, and returning a text of just the top mentions
keep_top_mentions = function(input_string){
software_instance <- input_string
software_instance <- toString(software_instance)
software_instance <- as.list(unlist(strsplit(software_instance, ', ')))
software_instance <- data.frame(software_instance)
software_instance <- as.data.frame(t(software_instance))
names(software_instance)[1] <- "software"

culled_df <- inner_join(software_instance, topsoftwares)
culled_software <- toString(culled_df$software)
return(culled_software)
}

# apply the function to each row in the software column of our data
culled_data$software <- sapply(culled_data$software, function(x) keep_top_mentions(x))

# only keep the rows of data where the top software is mentioned
new_data <- culled_data %>%
  filter(software!="")


## formating for Andrew's Python script
# remove the spaces
new_data$software <- sapply(new_data$software, function(x) str_replace_all(x, " ", ""))
# create the month and year columns
new_data$month <- format(as.Date(new_data$publish_time), format="%m")
new_data$year <- format(as.Date(new_data$publish_time), format="%Y")

# write the culled dataset to a csv
write.csv(new_data,"top_software_dataset.csv", row.names = FALSE)
